[package]
name = "sp-lightclient"
version = "0.1.0"
authors = ["Vedhavyas Singareddi <ved@subspace.network>"]
edition = "2021"
license = "Apache-2.0"
homepage = "https://subspace.network"
repository = "https://github.com/subspace/subspace"
description = "Light client substrate primitives for Subspace"
include = [
    "/src",
    "/Cargo.toml",
    "/README.md",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codec = { package = "parity-scale-codec", version = "3.1.2", default-features = false }
scale-info = { version = "2.1.1", default-features = false, features = ["derive"] }
schnorrkel = { version = "0.9.1", default-features = false, features = ["u64_backend"] }
sp-arithmetic = { version = "5.0.0", default-features = false, git = "https://github.com/subspace/substrate", rev = "752980bf4a16488f0b37a4741bdefdd2f90e93bf" }
sp-consensus-slots = { version = "0.10.0-dev", default-features = false, git = "https://github.com/subspace/substrate", rev = "752980bf4a16488f0b37a4741bdefdd2f90e93bf" }
sp-consensus-subspace = { version = "0.1.0", path = "../sp-consensus-subspace", default-features = false }
sp-runtime = { version = "6.0.0", default-features = false, git = "https://github.com/subspace/substrate", rev = "752980bf4a16488f0b37a4741bdefdd2f90e93bf" }
sp-std = { version = "4.0.0-dev", default-features = false, git = "https://github.com/subspace/substrate", rev = "752980bf4a16488f0b37a4741bdefdd2f90e93bf" }
subspace-core-primitives = { version = "0.1.0", path = "../subspace-core-primitives", default-features = false }
subspace-solving = { version = "0.1.0", path = "../subspace-solving", default-features = false }
subspace-verification = { version = "0.1.0", path = "../subspace-verification", default-features = false }

[dev-dependencies]
frame-support = { version = "4.0.0-dev", git = "https://github.com/subspace/substrate", rev = "752980bf4a16488f0b37a4741bdefdd2f90e93bf" }
rand_core = "0.6.3"

[features]
default = ["std"]
std = [
    "codec/std",
    "scale-info/std",
    "schnorrkel/std",
    "sp-arithmetic/std",
    "sp-consensus-slots/std",
    "sp-consensus-subspace/std",
    "sp-runtime/std",
    "sp-std/std",
    "subspace-core-primitives/std",
    "subspace-solving/std",
    "subspace-verification/std"
]
