[package]
name = "domain-client-executor"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2021"

[dependencies]
# Substrate dependencies
sc-client-api = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f" }
sc-consensus = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f" }
sc-network = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f" }
sc-transaction-pool-api = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f" }
sc-utils = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f" }
sp-api = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f" }
sp-blockchain = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f" }
sp-block-builder = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f" }
sp-consensus = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f" }
sp-consensus-slots = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f" }
sp-core = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f" }
sp-keystore = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f" }
sp-runtime = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f" }
sp-trie = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f" }

# Other dependencies
# Not using `blake2` crate due to https://github.com/RustCrypto/hashes/issues/360
blake2-rfc = "0.2.18"
codec = { package = "parity-scale-codec", version = "3.1.5", features = [ "derive" ] }
crossbeam = "0.8.2"
futures = { version = "0.3.21", features = ["compat"] }
futures-timer = "3.0.1"
rand = "0.8.5"
rand_chacha = "0.3.1"
merkletree = "0.22.0"
parking_lot = "0.12.1"
schnorrkel = "0.9.1"
tracing = "0.1.36"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["macros"] }

domain-block-builder = { path = "../block-builder" }
domain-client-executor-gossip = { path = "../executor-gossip" }
domain-runtime-primitives = { path = "../../primitives/runtime" }
sp-domains = { path = "../../../crates/sp-domains" }
sp-domain-digests = { path = "../../primitives/digests" }
sp-domain-tracker = { path = "../../primitives/domain-tracker" }
subspace-fraud-proof = { path = "../../../crates/subspace-fraud-proof" }
subspace-core-primitives = { path = "../../../crates/subspace-core-primitives" }
subspace-runtime-primitives = { path = "../../../crates/subspace-runtime-primitives" }
system-runtime-primitives = { path = "../../primitives/system-runtime" }

[dev-dependencies]
domain-test-service = { path = "../../test/service" }
pallet-balances = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f" }
pallet-domains = { path = "../../../crates/pallet-domains" }
sc-cli = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f", default-features = false }
sc-service = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f", default-features = false }
sc-transaction-pool = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f" }
sp-keyring = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f" }
sp-state-machine = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f" }
subspace-test-runtime = { path = "../../../test/subspace-test-runtime" }
subspace-test-service = { path = "../../../test/subspace-test-service" }
substrate-test-runtime-client = { path = "../../../substrate/substrate-test-runtime-client" }
substrate-test-utils = { git = "https://github.com/subspace/substrate", rev = "66d3f73c5ef66c975fa5f54b6736ccd6821e395f" }
tempfile = "3.3.0"
