[package]
name = "subspace-farmer"
description = "Farmer for the Subspace Network Blockchain"
license = "MIT OR Apache-2.0"
version = "0.1.0"
authors = ["Nazar Mokrynskyi <nazar@mokrynskyi.com>"]
edition = "2021"
include = [
    "/src",
    "/Cargo.toml",
    "/README.md",
]

[dependencies]
anyhow = "1.0.61"
async-trait = "0.1.57"
base58 = "0.2.0"
bitvec = "1.0.1"
blake2-rfc = "0.2.18"
bytesize = "1.1.0"
clap = { version = "4.0.22", features = ["color", "derive"] }
derive_more = "0.99.17"
dirs = "4.0.0"
event-listener-primitives = "2.0.1"
fdlimit = "0.2"
futures = "0.3.21"
hex = { version = "0.4.3", features = ["serde"] }
jsonrpsee = { version = "0.15.1", features = ["client", "macros", "server"] }
memmap2 = "0.5.7"
num-traits = "0.2.15"
parity-db = "0.3.17"
parity-scale-codec = "3.1.5"
parking_lot = "0.12.1"
rand = "0.8.5"
schnorrkel = "0.9.1"
serde = { version = "1.0.143", features = ["derive"] }
serde_json = "1.0.83"
static_assertions = "1.1.0"
std-semaphore = "0.1.0"
ss58-registry = "1.25.0"
subspace-archiving = { version = "0.1.0", path = "../subspace-archiving" }
subspace-farmer-components = { version = "0.1.0", path = "../subspace-farmer-components" }
subspace-solving = { version = "0.1.0", path = "../subspace-solving" }
subspace-core-primitives = { version = "0.1.0", path = "../subspace-core-primitives" }
subspace-networking = { version = "0.1.0", path = "../subspace-networking" }
subspace-rpc-primitives = { version = "0.1.0", path = "../subspace-rpc-primitives" }
substrate-bip39 = "0.4.4"
tempfile = "3.3.0"
thiserror = "1.0.32"
tokio = { version = "1.20.1", features = ["macros", "parking_lot", "rt-multi-thread", "signal"] }
tracing = "0.1.36"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
ulid = { version = "1.0.0", features = ["serde"] }
zeroize = "1.5.7"

# The only triple tested and confirmed as working in `jemallocator` crate is `x86_64-unknown-linux-gnu`
[target.'cfg(all(target_arch = "x86_64", target_vendor = "unknown", target_os = "linux", target_env = "gnu"))'.dependencies]
jemallocator = "0.5.0"

[dev-dependencies]
rayon = "1.5.3"
